# Generated by Django 4.0.4 on 2022-05-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_squashed_0018_alter_user_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='upload',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
