# Generated by Django 4.0.4 on 2022-05-31 14:23

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_image_label_alter_upload_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[app.validators.validate_max_duration, app.validators.validate_min_duration]),
        ),
    ]
