# Generated by Django 4.0.4 on 2022-05-28 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_thumbnail_alter_image_upload_alter_upload_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='tier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tier'),
            preserve_default=False,
        ),
    ]
