# Generated by Django 4.0.4 on 2022-05-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_max_heigh_thumbnail_max_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='label',
            field=models.CharField(default='orig', max_length=50),
            preserve_default=False,
        ),
    ]
