# Generated by Django 4.0.4 on 2022-05-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_tier_is_original_allowed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thumbnail',
            options={'ordering': ['-max_height']},
        ),
    ]
