# Generated by Django 4.0.4 on 2022-05-30 17:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_thumbnail_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 30, 17, 27, 15, 226460, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
            preserve_default=False,
        ),
    ]
