# Generated by Django 4.0.4 on 2022-05-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_upload_created_upload_duration_upload_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
            
        ),
        migrations.AlterField(
            model_name='upload',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
