# Generated by Django 4.0.4 on 2022-05-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_upload_duration_alter_upload_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='is_expiring_allowed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
