# Generated by Django 4.0.4 on 2022-05-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_tier_is_expiring_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tier',
            name='is_expiring_allowed',
            field=models.BooleanField(verbose_name='Is setting expire time allowed?'),
        ),
        migrations.AlterField(
            model_name='tier',
            name='is_original_allowed',
            field=models.BooleanField(verbose_name='Is uploading of original picture allowed?'),
        ),
        migrations.AlterField(
            model_name='tier',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Tier name'),
        ),
    ]
